/* generated by Makefile.devel from version.sh */
#define PACKAGE_NAME "Based CLISP"
#define PACKAGE_TARNAME "clisp"
#define PACKAGE_VERSION "2.49.93+ (2018-02-18)"
#define PACKAGE_STRING "Based CLISP 2.49.93+ (2018-02-18)"
#define PACKAGE_BUGREPORT "http://getgle.org/"
